<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <BaseOutputPath>..\..\bin\</BaseOutputPath>
    <TieredPGO>true</TieredPGO>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FirebirdSql.Data.FirebirdClient" Version="10.3.4" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
    <PackageReference Include="MySqlConnector" Version="2.6.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.200" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SearchEngine\SearchEngine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SearchEngine.Service.Tests" />
  </ItemGroup>

</Project>
