@host = http://localhost:5037

###

# Для проверки ошибок TooManyDocuments и DocumentTextTooLong
# удобно временно уменьшить настройки сервиса:
#
# SearchEngineService:MaxDocumentCount = 1
# SearchEngineService:MaxDocumentTextLength = 5
#
# В Docker это можно сделать так:
#
# docker run --rm -p 8080:8080 `
#   -e SearchEngineService__MaxDocumentCount=1 `
#   -e SearchEngineService__MaxDocumentTextLength=5 `
#   searchengine-service:dev

GET {{host}}/health

###

GET {{host}}/ready

###

GET {{host}}/v1/info

###

GET {{host}}/v1/config

###

# Настройки snapshot индекса можно переопределить через переменные окружения:
#
# SearchEngineService__Snapshot__IsEnabled=true
# SearchEngineService__Snapshot__FilePath=data/search-index-snapshot.json

GET {{host}}/v1/search/options

###

GET {{host}}/v1/index

###

POST {{host}}/v1/index/validate
Content-Type: application/json

{
  "isPhoneticSearch": false,
  "documents": [
    {
      "id": 1,
      "text": "Иванов Сергей Петрович"
    },
    {
      "id": 2,
      "text": "Папандопуло Александр"
    },
    {
      "id": 3,
      "text": ""
    }
  ]
}

###

POST {{host}}/v1/index
Content-Type: application/json

{
  "isPhoneticSearch": false,
  "documents": [
    {
      "id": 1,
      "text": "Иванов Сергей Петрович"
    },
    {
      "id": 2,
      "text": "Папандопуло Александр"
    },
    {
      "id": 3,
      "text": "Красный велосипед"
    }
  ]
}

###

POST {{host}}/v1/search
Content-Type: application/json

{
  "query": "Ivanov",
  "matchMode": "AllTerms",
  "searchType": "ExactSearch",
  "searchLocation": "BeginWord"
}

###

POST {{host}}/v1/index
Content-Type: application/json

{
  "isPhoneticSearch": true,
  "documents": [
    {
      "id": 1,
      "text": "Иванов Сергей Петрович"
    },
    {
      "id": 2,
      "text": "Папандопуло Александр"
    },
    {
      "id": 3,
      "text": "Красный велосипед"
    }
  ]
}

###

POST {{host}}/v1/index/restore

###

POST {{host}}/v1/search
Content-Type: application/json

{
  "query": "Ivanov",
  "matchMode": "AllTerms",
  "searchType": "ExactSearch",
  "searchLocation": "BeginWord"
}

###

POST {{host}}/v1/search
Content-Type: application/json

{
  "query": "Papandopulo",
  "matchMode": "AllTerms",
  "searchType": "ExactSearch",
  "searchLocation": "BeginWord"
}

###

POST {{host}}/v1/search
Content-Type: application/json

{
  "query": "Папандопула",
  "matchMode": "AllTerms",
  "searchType": "ExactSearch",
  "searchLocation": "BeginWord"
}

###
# Ниже команды для проверки ограничений количества документов и длинны строки

POST {{host}}/v1/index
Content-Type: application/json

{
  "isPhoneticSearch": false,
  "documents": [
    {
      "id": 1,
      "text": "Иванов Сергей Петрович"
    },
    {
      "id": 2,
      "text": "Папандопуло Александр"
    }
  ]
}

###

POST {{host}}/v1/index
Content-Type: application/json

{
  "isPhoneticSearch": false,
  "documents": [
    {
      "id": 1,
      "text": "Очень длинный текст"
    }
  ]
}
