@host = http://localhost:5037

GET {{host}}/health

###

GET {{host}}/v1/info

###

GET {{host}}/v1/index

###

POST {{host}}/v1/index/validate
Content-Type: application/json

{
  "isPhoneticSearch": true,
  "documents": [
    {
      "id": 1,
      "text": "Иванов Сергей Петрович"
    },
    {
      "id": 2,
      "text": "Папандопуло Александр"
    },
    {
      "id": 3,
      "text": ""
    }
  ]
}

###

POST {{host}}/v1/index
Content-Type: application/json

{
  "isPhoneticSearch": false,
  "documents": [
    {
      "id": 1,
      "text": "Иванов Сергей Петрович"
    },
    {
      "id": 2,
      "text": "Папандопуло Александр"
    },
    {
      "id": 3,
      "text": "Красный велосипед"
    }
  ]
}

###

POST {{host}}/v1/search
Content-Type: application/json

{
  "query": "Иванов"
}

###

POST {{host}}/v1/search
Content-Type: application/json

{
  "query": "лосип",
  "searchType": "ExactSearch",
  "searchLocation": "InWord"
}

###

POST {{host}}/v1/search
Content-Type: application/json

{
  "query": "Иван",
  "searchType": "ExactSearch",
  "searchLocation": "BeginWord"
}